// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXnj--hqnGk1XaZG5s-J8soMJTbR2UxK8',
    appId: '1:331739518901:web:69913e4c2ab6308cbcabfc',
    messagingSenderId: '331739518901',
    projectId: 'chat-app-c57ba',
    authDomain: 'chat-app-c57ba.firebaseapp.com',
    storageBucket: 'chat-app-c57ba.appspot.com',
    measurementId: 'G-H6F3Z1BXTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANRUYKvSy3fQvCzOZ0PWNk1Yjx1MOOmDw',
    appId: '1:331739518901:android:16ecf1960bfd4d14bcabfc',
    messagingSenderId: '331739518901',
    projectId: 'chat-app-c57ba',
    storageBucket: 'chat-app-c57ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfOqN2eNHcuPt7Tb_6ThBVUQHUDjWd8KQ',
    appId: '1:331739518901:ios:730a42f341dbb0d9bcabfc',
    messagingSenderId: '331739518901',
    projectId: 'chat-app-c57ba',
    storageBucket: 'chat-app-c57ba.appspot.com',
    iosClientId: '331739518901-orfpdjilsfotql5k14r91b644jg1db73.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfOqN2eNHcuPt7Tb_6ThBVUQHUDjWd8KQ',
    appId: '1:331739518901:ios:413dfcdda7b51964bcabfc',
    messagingSenderId: '331739518901',
    projectId: 'chat-app-c57ba',
    storageBucket: 'chat-app-c57ba.appspot.com',
    iosClientId: '331739518901-rjrdkd70jq2frlcap9k8nvhotpmk2iev.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat.RunnerTests',
  );
}
